# Generated by Django 4.1.5 on 2023-01-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('intrest_rate', models.IntegerField()),
                ('term_period', models.IntegerField()),
                ('disbursement_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
