# Generated by Django 4.1.5 on 2023-01-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userloan_loan_repayment_amount_user_aadhar_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoan',
        ),
        migrations.AddField(
            model_name='loan',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
