# Generated by Django 4.1.5 on 2023-01-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_credit_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('loan_id', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('principal', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
